name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: yourusername/hello-world-ui

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Image Tag
        id: vars
        run: echo "TAG=1.0-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${TAG} .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          format: table
          exit-code: '1'
          severity: CRITICAL,HIGH

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${TAG}

                - name: Update Helm Chart Repository
        env:
          HELM_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
          TAG: ${{ env.TAG }}
        run: |
          git clone https://x-access-token:${HELM_TOKEN}@github.com/ras-km/hello-world-helm.git
          cd hello-world-helm/hello-world

          sed -i "s/tag:.*/tag: \"${TAG}\"/" values.yaml

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add values.yaml
          git commit -m "Update image tag to ${TAG}"

          git push

